title: Martyn Minker # your name (or website title) here
logo: "MartynM1982.github.io/images/MM photo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A Junior Python developer with a passion for coding and developing my skills. Eager to learn and always looking for new opportunities to expand my career further.
  <br><br>
  With a real drive for what I do, I am a conscientious, ambitious, self-motivated and hardworking professional with strong communication skills and an accurate and precise working style.
  <br><br>
  <a href="https://www.linkedin.com/in/martyn-minker/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
